 apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
 kind: Ingress
 metadata:
   name: postgresql-ha-pgpool
   annotations:
     nginx.ingress.kubernetes.io/rewrite-target: /
 spec:
   rules:
   - host: postgres-dev.cloud.lan
     http:
       paths:
       - path: /
         backend:
           serviceName: postgresql-ha-pgpool
           servicePort: 5432
